"""empty message

Revision ID: 104daec96def
Revises: e1bddc19548c
Create Date: 2020-03-21 17:48:16.439107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104daec96def'
down_revision = 'e1bddc19548c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('duration', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'duration')
    # ### end Alembic commands ###
