"""empty message

Revision ID: 2b5ebb513123
Revises: a3ee85ac9f7a
Create Date: 2020-03-15 20:43:18.958204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5ebb513123'
down_revision = 'a3ee85ac9f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('school', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'school')
    # ### end Alembic commands ###
