"""empty message

Revision ID: 7575ecabbdb7
Revises: d6207d6aea6c
Create Date: 2018-05-04 17:34:40.129970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7575ecabbdb7'
down_revision = 'd6207d6aea6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('signature', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'signature')
    # ### end Alembic commands ###
