"""empty message

Revision ID: 7c80e54d8227
Revises: 2b5ebb513123
Create Date: 2020-03-16 13:51:46.083365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c80e54d8227'
down_revision = '2b5ebb513123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('school', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'school')
    # ### end Alembic commands ###
