"""empty message

Revision ID: 808c3ac94a38
Revises: 7575ecabbdb7
Create Date: 2018-05-04 18:26:51.391261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '808c3ac94a38'
down_revision = '7575ecabbdb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'signature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('signature', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
