"""empty message

Revision ID: f7a7803459c0
Revises: 9b3bb13d4926
Create Date: 2018-05-04 22:15:14.836944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a7803459c0'
down_revision = '9b3bb13d4926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_info', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.drop_column('user_info', 'user_id')
    # ### end Alembic commands ###
